<?php
/************************************************************************/
/* [Google-Site-Map] 1.0 by TheGhost              			            */
/* =================================                                    */
/* Copyright (c) 2021 by The 86it Developers Network          			*/
/* http://www.86it.us                                                   */
/************************************************************************/
if (!defined('MODULE_FILE')) 
die ("You can't access this file directly...");

$module_name = basename(dirname(__FILE__));

global $prefix, $db, $sitename, $currentlang, $admin, $multilingual, $module_name, $admin_file, $user_prefix;

$result = $db->sql_query('SELECT * FROM `'.$prefix.'_jmap`');

while ($row=$db->sql_fetchrow($result)):
    $nametask = $row['name'];
    $value = $row['value'];
    $conf[$nametask]=$value;
endwhile;

$db->sql_freeresult($result);
$xml = $conf['xml'];
$ndown = $conf['ndown'];
$nnews = $conf['nnews'];
$nrev = $conf['nrev'];
$ntopics = $conf['ntopics'];
$nuser = $conf['nuser'];

//---------------------- XML BEGIN -----------------
if($xml):
//OPEN FILE
$var=@fopen(NUKE_BASE_DIR."sitemap.xml","w+");
// HEADER
@fwrite($var, "<?xml version=\"1.0\" encoding=\"utf-8\" ?>
<!-- Google Site Map File Generated by Google-Site-Map http://www.86it.us -->
<urlset xmlns=\"http://www.google.com/schemas/sitemap/0.84\">\n");
else: 
//DELETE CONTENT
$var=@fopen(NUKE_BASE_DIR."sitemap.xml","w+");
@fclose($var);
endif;
//---------------------- XML END -----------------


if (file_exists(NUKE_MODULES_DIR.$module_name.'/language/lang-'.$currentlang.'.php')):
	include_once(NUKE_MODULES_DIR.$module_name.'/language/lang-'.$currentlang.'.php');
else:
	include_once(NUKE_MODULES_DIR.$module_name.'/language/lang-english.php');
endif;

function downloads_subs($cid, $spaces, $xml) 
{
    $result4 = $db->sql_query("SELECT cid, title FROM " . $prefix . "_downloads_categories WHERE active=1 AND parentid=$cid1 ORDER BY title");
}

include_once(NUKE_BASE_DIR.'header.php');

Opentable();

print '<div align="center"><strong>'._GOOGLE_MAP.' '.$sitename.'</strong></div>';
print '<div align="center">';
print '<font color="violet"><i style="vertical-align: middle;" class="fa fa-unlock-alt"></i></font>&nbsp;<font size="1">(EVERYONE)</font>&nbsp;';
print '<font color="green"><i style="vertical-align: middle;" class="fa fa-unlock-alt"></i></font>&nbsp;<font size="1">(EVERYONE)</font>&nbsp;';
print '<font color="lime"><i style="vertical-align: middle;" class="fa fa-unlock-alt"></i></font>&nbsp;<font size="1">(EVERYONE)</font>&nbsp;';
print '<font color="aqua"><i style="vertical-align: middle;" class="fa fa-unlock-alt"></i></font>&nbsp;<font size="1">(EVERYONE)</font>&nbsp;';
print '<font color="#FF0000"><i style="vertical-align: middle;" class="fa fa-lock"></i></font>&nbsp;<font size="1">(REGISTERED USERS ONLY)</font>&nbsp;';
print '</div><br/>';

print '<div align="center">';
print '<table style="background-color:#70163C; height:100%; width:50%;" class="googlesitemap" align="center" border="5" cellpadding="15" cellspacing="20" dir="ltr" id="googlesitemap">';
print '<tbody>';
print '<tr>';
print '<td>';

print '<table align="center" border="0">';

print '<tr><td><font color="aqua"><i style="vertical-align: middle;" class="fa fa-unlock-alt"></i></td><td><a href="'.$nukeurl.'">Homepage</a></td></tr>'."\n";

$result2 = $db->sql_query("SELECT `title`, `custom_title`, `view`, `groups` FROM `" . $prefix . "_modules` WHERE `active` =1 ORDER BY `custom_title`");

while ($row2 = $db->sql_fetchrow($result2)): 

	$the_module_title = $row2['custom_title'];
	
	$link = $row2['title'];
	
	$permission = $row2['view'];
	
	$groups = $row2['groups'];
    
	$show = true;

	echo"<tr><td>";

	if ($permission < 3): 
		print '<font color="lime"><i style="vertical-align: middle;" class="fa fa-unlock-alt"></i>';
	elseif ($permission == 4 && is_admin()): 
	    print '<font color="lime"><i style="vertical-align: middle;" class="fa fa-unlock-alt"></i>';
	elseif ($permission == 6 && !empty($groups) && is_array($groups)): 

	    $ingroup = false;
	    global $userinfo;
	
	    foreach ($groups as $group): 
		     if (isset($userinfo['groups'][$group])) 
		     $ingroup = true;
	    endforeach;
		
		if (!$ingroup): 
	        print '<font color="lime"><i style="vertical-align: middle;" class="fa fa-unlock-alt"></i>';
		else: 
	        print '<font color="#FF0000"><i class="fa fa-lock"></i></font>&nbsp;';
			$show = false;
	    endif;
	 
	else: 
		print '<font color="#FF0000"><i class="fa fa-lock"></i></font>&nbsp;';
		$show = false;
	endif;
	
	print '</td>'."\n";

	print '<td><a href="modules.php?name='.$link.'">'.$the_module_title.'</a></td></tr>'."\n";

	switch($link) 
	{
		case 'Downloads':
	
			$result3 = $db->sql_query("SELECT `cid`, `title` FROM `".$prefix."_downloads_categories` WHERE `active`=1 AND `parentid`=0 ORDER BY `title`");
	
			while ($row3 = $db->sql_fetchrow($result3)): 
				
				$titolodown = $row3['title'];
			
				$cid1 = $row3['cid'];
			
				print '<tr><td>&nbsp;</td><td><font color="violet"><i style="vertical-align: absmiddle;" class="fa fa-unlock-alt"></i></font> <a href="modules.php?name=Downloads&amp;cid='.$cid1.'">'.$titolodown.'</a></td>';
			
				if($xml)
                @fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=Downloads&amp;cid='.$cid1.'</loc></url>'."\n");
         
			    $result4 = $db->sql_query('SELECT `cid`, `title` FROM `'.$prefix.'_downloads_categories` WHERE `active`=1 AND `parentid`="'.$cid1.'" ORDER BY `title`');
			
				while ($row4 = $db->sql_fetchrow($result4)): 
				
					$titolodown2 = $row4['title'];
				
					$cid2 = $row4['cid'];
				
					print '<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;<font color="green"><i style="vertical-align: middle;" class="fa fa-unlock-alt"></i></font> <a href="modules.php?name=Downloads&amp;cid='.$cid2.'">'.$titolodown2.'</a></td>';
				
					if($xml)
                    @fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=Downloads&amp;cid='.$cid2.'</loc></url>'."\n");
                
				   $result4b = $db->sql_query('SELECT `cid`, `lid`, `title` FROM `'.$prefix.'_downloads_downloads` WHERE `active`= 1 AND `cid`="'.$cid2.'" ORDER BY `hits` LIMIT 0,'.$ndown);
                
				    while ($row4b = $db->sql_fetchrow($result4b)): 
					
        				$titolodown3=$row4b['title'];
        			
						$cid3=$row4b['lid'];
        			
						print '<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="modules/Google-Site-Map/images/catt.gif" alt="cat"> <a href="modules.php?name=Downloads&amp;op=getit&amp;lid='.$cid3.'">'.$titolodown3.'</a></td>';
        			
						if($xml)
                        @fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=Downloads&amp;op=getit&amp;lid='.$cid3.'</loc></url>'."\n");
                    endwhile;
                    $db->sql_freeresult($result4b);
                endwhile;
                $db->sql_freeresult($result4);
			endwhile;
            $db->sql_freeresult($result3);
		break;
		
		case 'File_Repository':

			$result3 = $db->sql_query('SELECT `cid`, `cname` FROM `'.$prefix.'_file_repository_categories` WHERE `parentid`= 0 ORDER BY `cname`');
			
			while ($row3 = $db->sql_fetchrow($result3)):

				$titolodown = $row3['cname'];
				
				$cid1 = $row3['cid'];
				
				print '<tr><td>&nbsp;</td><td><font color="violet"><i style="vertical-align: absmiddle;" class="fa fa-unlock-alt"></i></font> <a href="modules.php?name=File_Repository&amp;cid='.$cid1.'">'.$titolodown.'</a></td>';
				
				if($xml)
				@fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=File_Repository&amp;cid='.$cid1.'</loc></url>'."\n");

				$result3b = $db->sql_query('SELECT `cid`, `did`, `title` FROM `'.$prefix.'_file_repository_items` WHERE `cid`="'.$cid1.'" ORDER BY `hits` LIMIT 0,'.$ndown);
				
				while ($row3b = $db->sql_fetchrow($result3b)):

					$titolodown3 = $row3b['title'];
					
					$cid3 = $row3b['did'];
					
					print '<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="modules/Google-Site-Map/images/catt.gif" alt="cat"> <a href="modules.php?name=File_Repository&amp;&action=view&amp;did='.$cid3.'">'.$titolodown3.'</a></td>';					
					
					if($xml)
					@fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=File_Repository&amp;action=view&amp;did='.$cid3.'</loc></url>'."\n");

                endwhile;
				                
                $db->sql_freeresult($result3b);	

                $result4 = $db->sql_query('SELECT `cid`, `cname` FROM `'.$prefix.'_file_repository_categories` WHERE `parentid`="'.$cid1.'" ORDER BY `cname`');
				
				while ($row4 = $db->sql_fetchrow($result4)):

					$titolodown2 = $row4['cname'];
					
					$cid2 = $row4['cid'];
					
					print '<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;<font color="green"><i style="vertical-align: middle;" class="fa fa-unlock-alt"></i></font> <a href="modules.php?name=File_Repository&amp;cid='.$cid2.'">'.$titolodown2.'</a></td>';
					
					if($xml)
					@fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=File_Repository&amp;cid='.$cid2.'</loc></url>'."\n");

					$result4b = $db->sql_query('SELECT `cid`, `did`, `title` FROM `'.$prefix.'_file_repository_items` WHERE `cid`="'.$cid2.'" ORDER BY `hits` LIMIT 0,'.$ndown);
					
					while ($row4b = $db->sql_fetchrow($result4b)):

						$titolodown4 = $row4b['title'];
						
						$cid4 = $row4b['did'];
						
						print '<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="modules/Google-Site-Map/images/catt.gif" alt="cat"> <a href="modules.php?name=File_Repository&amp;&action=view&amp;did='.$cid4.'">'.$titolodown4.'</a></td>';
						
						if($xml)
						@fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=File_Repository&amp;action=view&amp;did='.$cid4.'</loc></url>'."\n");

					endwhile;
					$db->sql_freeresult($result4b);
				endwhile;
				$db->sql_freeresult($result4);
			endwhile;
            $db->sql_freeresult($result3);
		break;		
		

		case 'Forums':

			$result5 = $db->sql_query('SELECT `cat_id`, `cat_title` FROM `'.$prefix.'_bbcategories` ORDER BY `cat_order`');

			while ($row5 = $db->sql_fetchrow($result5)): 
			
				$titolocatf = $row5['cat_title'];
				$cat_id = $row5['cat_id'];

				//Check to make sure its not a blank category
				$number_of_forums = $db->sql_numrows($db->sql_query('SELECT * FROM '.$prefix.'_bbforums WHERE `cat_id`="'.$cat_id.'" AND auth_view < 2 AND auth_read < 2 ORDER BY forum_order'));
				
				if ($number_of_forums <= 0) 
				continue;

				print '<tr><td>&nbsp;</td><td><font color="violet"><i style="vertical-align: absmiddle;" class="fa fa-unlock-alt"></i></font> <a href="modules.php?name=Forums&amp;file=index&amp;c='.$cat_id.'">'.$titolocatf.'</a></td>';
		        
				if($xml)
                @fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=Forums&amp;file=index&amp;c='.$cat_id.'</loc></url>'."\n");
                
				$result6 = $db->sql_query('SELECT `forum_name`,`forum_id`,`auth_view`,`auth_read` FROM `'.$prefix.'_bbforums` WHERE `cat_id`="'.$cat_id.'" AND `auth_view`< 2 AND `auth_read` < 2 ORDER BY `forum_order`');
				
				while ($row6 = $db->sql_fetchrow($result6)): 
				
					$titoloforum = $row6['forum_name'];
					$fid = $row6['forum_id'];
					$auth_view = $row6['auth_view'];
					$auth_read = $row6['auth_read'];
				
					print '<tr><td>&nbsp;</td><td>';
					
					if ($auth_view && !is_user()): 
					
						print '<font color="#FF0000"><i class="fa fa-lock"></i></font>&nbsp;';
						print $titoloforum.'</td></tr>';
					 
					else: 
					
						print '&nbsp;&nbsp;&nbsp;&nbsp;<font color="green"><i style="vertical-align: absmiddle;" class="fa fa-unlock-alt"></i></font>';
						print  '<a href="modules.php?name=Forums&amp;file=viewforum&amp;f='.$fid.'">'.$titoloforum.'</a></td></tr>';
    			        
						if($xml)
                        @fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=Forums&amp;file=viewforum&amp;f='.$fid.'</loc><changefreq>daily</changefreq></url>'."\n");
                        
						$resultT = $db->sql_query('SELECT topic_title, topic_id FROM '.$prefix.'_bbtopics WHERE `forum_id`="'.$fid.'" ORDER BY topic_id DESC LIMIT 0,'.$ntopics);
						
						while($rowT = $db->sql_fetchrow($resultT)): 
						
						    print '<tr><td>&nbsp;</td><td>';
							print '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="modules/Google-Site-Map/images/catt.gif" alt="cat">';
							print '<a href="modules.php?name=Forums&amp;file=viewtopic&amp;t='.$rowT[topic_id].'">'.$rowT[topic_title].'</a></td>';
							
							if($xml)
                            @fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=Forums&amp;file=viewtopic&amp;t='.$rowT[topic_id].'</loc><changefreq>daily</changefreq></url>'."\n");
                        
						endwhile;
                       $db->sql_freeresult($resultT);
					endif;
				endwhile;
				$db->sql_freeresult($result6);
			endwhile;
			$db->sql_freeresult($result5);
		break;

		case 'Sections':
			
			$result7 = $db->sql_query('select `secid`, `secname`, `image` from `'.$prefix.'_sections` order by `secname`');
			
			while ($row7 = $db->sql_fetchrow($result7)): 
			
				$secid = $row7['secid'];
				
				$secname = $row7['secname'];
				
				$view = $row7['view'];
			
				print '<tr><td>&nbsp;</td><td>';
			
				if ($view==1) 
					print '<font color="#FF0000"><i class="fa fa-lock"></i></font>&nbsp;';
				else 
					print '&nbsp;&nbsp;&nbsp;&nbsp;<i style="vertical-align: absmiddle;" class="fa fa-unlock-alt"></i></font> ';
				
				print '<a href="modules.php?name=Sections&amp;op=listarticles&amp;secid='.$secid.'">'.$secname.'</a></td>';
				
				if($xml)
			        @fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=Sections&amp;op=listarticles&amp;secid='.$secid.'</loc></url>'."\n");
			endwhile;
			$db->sql_freeresult($result7);
		break;

		case 'Web_Links':
            
			$result8 = $db->sql_query('SELECT `cid`, `title` from `'.$prefix.'_links_categories` where `parentid`="'.$cid.'" order by `title`');
			
			while ($row8 = $db->sql_fetchrow($result8)): 
			
				$titololink = $row8['title'];
			
				$cid1 = $row8['cid'];
			
				print '<tr><td>&nbsp;</td><td><font color="green"><i style="vertical-align: absmiddle;" class="fa fa-unlock-alt"></i></font> <a href="modules.php?name=Web_Links&amp;l_op=viewlink&amp;cid='.$cid1.'">'.$titololink.'</a></td>';
			
				if($xml)
	           @fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=Web_Links&amp;l_op=viewlink&amp;cid='.$cid1.'</loc></url>'."\n");
            
			endwhile;
            $db->sql_freeresult($result8);
		break;

		case 'Blog_Topics':
			
			$result9 = $db->sql_query("SELECT topictext,topicid FROM ".$prefix."_topics ORDER BY topictext");
			
			while ($row9 = $db->sql_fetchrow($result9)):
				$topiclink=$row9['topictext'];
				$cidtopic=$row9['topicid'];
				print '<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;<font color="green"><i style="vertical-align: absmiddle;" class="fa fa-unlock-alt"></i></font> <a href="modules.php?name=Blog_Topics&amp;cid='.$cidtopic.'">'.$topiclink.'</a></td>';
				if($xml)
		        @fwrite($var, "<url><loc>$nukeurl/modules.php?name=Blog_Topics&amp;cid=$cidtopic</loc></url>\n");

            endwhile;
            $db->sql_freeresult($result9);
		break;

		case 'Blog':
			
			$result10 = $db->sql_query('SELECT `title`, `sid` FROM `'.$prefix.'_stories` ORDER BY `sid` DESC LIMIT 0,'.$nnews);
			
			while ($row10 = $db->sql_fetchrow($result8)): 

				$newslink = $row10['title'];
			
				$cidnews = $row10['sid'];

				print '<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;<font color="green"><i style="vertical-align: absmiddle;" class="fa fa-unlock-alt"></i></font> <a href="modules.php?name=Blog&amp;file=article&amp;sid='.$cidnews.'">'.$newslink.'</a></td>';
			
				if($xml)
			    @fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=Blog&amp;file=article&amp;sid='.$cidnews.'</loc></url>'."\n");
            endwhile;
			
            $db->sql_freeresult($result10);
		break;

		case 'Members_List':
		
			$result11 = $db->sql_query('SELECT `username`, `user_id` FROM `'.$user_prefix.'_users` ORDER BY `user_id` DESC LIMIT 0,'.$nuser);
		
		if ($show): 
		
			   while ($row11 = $db->sql_fetchrow($result11)): 
			   
				$user=$row11['username'];
			
				$ciduser=$row11['user_id'];

				print '<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;<font color="green"><i style="vertical-align: absmiddle;" class="fa fa-unlock-alt"></i></font> <a href="modules.php?name=Profile&amp;mode=viewprofile&amp;u='.$ciduser.'">'.$user.'</a></td>';

				if($xml)
			    @fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=Profile&amp;mode=viewprofile&amp;u='.$ciduser.'</loc></url>'."\n");

               endwhile;
            $db->sql_freeresult($result11);
		
		endif;
		break;

		case 'Reviews':
			
			$result12 = $db->sql_query('SELECT `title`, `id` FROM `'.$prefix.'_reviews` ORDER BY `id` DESC LIMIT 0,'.$nrev);
			
			while ($row12 = $db->sql_fetchrow($result12)): 
			
				$titrev=$row12['title'];
			
				$cidrev=$row12['id'];

				print '<tr><td></td><td>&nbsp;&nbsp;&nbsp;&nbsp;<font color="green"><i style="vertical-align: absmiddle;" class="fa fa-unlock-alt"></i></font> <a href="modules.php?name=Reviews&amp;rop=showcontent&amp;id='.$cidrev.'">'.$titrev.'</a></td>';
			
				if($xml)
			    @fwrite($var, '<url><loc>'.$nukeurl.'/modules.php?name=Reviews&amp;rop=showcontent&amp;id='.$cidrev.'</loc></url>'."\n");

            endwhile;
            $db->sql_freeresult($result12);
		break;
	}
endwhile;

$db->sql_freeresult($result2);

print '</table>';

if ( defined('facebook') ):	
global $content, $sid, $appID, $my_url;
print '<div id="fb-root"></div>'."\n";
print '<br /><script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v10.0&appId='.$appID.'&autoLogAppEvents=1" nonce="dv0pyfMc"></script>'."\n";
print '<div style="background-color: none" class="fb-like" data-href="https://'.$my_url.'/modules.php?name=Google-Site-Map" data-width="" data-layout="button_count" data-action="like" data-size="large" data-share="true"></div>'."\n";
endif;

print '</td>';
print '</tr>';
print '</tbody>';
print '</table>';
print '</div>';

print'
<script type="text/javascript">
 <!--
 function copy() {
   var w = 400;
   var h = 350;
   var l = Math.floor((screen.width-w)/2);
   var t = Math.floor((screen.height-h)/2);
      window.open("modules/Google-Site-Map/copyright.php","","width=" + w + ",height=" + h + ",top=" + t + ",left=" + l);
 }
 //-->
</script>';
print '<div align="center"><a href="javascript:copy()">&copy; Google Site Map</a></div>';

CloseTable();

if($xml)
{
// FOOTER XML
@fwrite($var, '</urlset>');
}
// FOOTER GRAPHIC
include_once(NUKE_BASE_DIR.'footer.php');

